
-- TAG

INSERT INTO TAG(id, name) VALUES ('5e471601-ef64-4214-bc83-4061eed36b01', 'heart');
INSERT INTO TAG(id, name) VALUES ('c76305d3-1b70-451e-b069-c083462fc0fb', 'pain');
INSERT INTO TAG(id, name) VALUES ('b675a989-2a2d-4b15-8f99-28b2d4ed6908', 'diabetes');
INSERT INTO TAG(id, name) VALUES ('a0a1376d-0267-4049-b75b-5e9984b08f1a', 'mood');

-- SPONSER
INSERT INTO SPONSOR(id, name, description) VALUES ('db07c874-4f65-44ff-b76e-21332982acac', 'Institude of Mood Research', 'Maecenas pretium quis ligula at sagittis. Cras porttitor sem quis mi consectetur pellentesque. Maecenas rutrum mattis tortor a finibus. Proin id eros et dui sodales bibendum. Aenean nibh urna, commodo non ultricies eget, malesuada vitae orci. Fusce quis tincidunt nunc, sed fringilla neque. Morbi eget tristique est, sit amet fermentum magna. Duis nec metus ut neque suscipit mattis.');
INSERT INTO SPONSOR(id, name, description) VALUES ('e1f4aacf-6162-4019-883c-911812aea583', 'Substance P Research', 'Morbi et venenatis est. Mauris felis orci, suscipit vitae ultrices sit amet, ultricies lacinia nisi. Morbi in aliquam felis. Nullam eget hendrerit nisl. Nunc est urna, porta tempus nulla tempus, sollicitudin posuere ante. Nunc laoreet nulla eget metus suscipit, nec suscipit libero semper. Fusce ac libero tortor.');
INSERT INTO SPONSOR(id, name, description) VALUES ('f39b1384-1e6d-4f45-b07c-8fef45616540', 'Doom Institute', 'Sed ornare arcu eget neque tincidunt volutpat. Praesent cursus eros eget enim fringilla, eget efficitur erat tincidunt. Proin massa leo, finibus in ultrices et, tincidunt eget nulla. Pellentesque in ultrices quam, quis pulvinar elit. Ut semper condimentum quam, at pharetra urna lobortis eu. Donec pharetra ante at magna egestas fermentum. Donec nec justo.');
INSERT INTO SPONSOR(id, name, description) VALUES ('3477a82b-9c71-45de-af94-11dd000fcf12', 'Loomhour Institute of Pain', 'Mauris tempus, arcu non mollis sodales, erat enim placerat odio, a laoreet orci ipsum ut leo. Proin vitae eros nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas sit amet mi quis tellus vulputate fringilla sed vel enim. In sit amet vulputate libero. Maecenas nibh lorem, tincidunt ac risus ut, lobortis aliquam nisl. Vivamus quis massa vestibulum, tristique enim eu, vehicula augue. Integer scelerisque nec tellus nec consectetur. Fusce dui nisi, fermentum in convallis ut, fringilla eget neque. Pellentesque vulputate commodo risus ac cursus. Fusce vitae lacinia ipsum. Donec sagittis dui ipsum, a euismod.');
INSERT INTO SPONSOR(id, name, description) VALUES ('8deea42b-73cf-48b5-bb72-2e7249182411', 'Heart Research of Cap', 'Donec nec tincidunt dolor, sit amet ultricies mauris. Proin euismod bibendum porttitor. Pellentesque consequat turpis felis. Aenean vel interdum justo. Donec a odio arcu. Nulla non erat eu urna scelerisque tempor vel eu ante. Morbi nisi lectus, suscipit a molestie nec, porttitor ut ante. Fusce congue.');


-- CLINICAL TRIAL TYPES
INSERT INTO CLINICAL_TRIAL_TYPE(id, name, clinical_trial_type_description) VALUES ('9de5c971-eec1-4624-bbdd-24705b42cf96', 'Quality of life', 'Also known as “supportive care,” this research explores ways to improve comfort and the quality of life for individuals with a chronic illness.');
INSERT INTO CLINICAL_TRIAL_TYPE(id, name, clinical_trial_type_description) VALUES ('09aef28a-cfba-4073-aa23-719bd94a0fc5', 'Treatment', 'Treatment research (also called “clinical trials”) generally involves an intervention such as medication, psychotherapy, new devices, or new approaches to surgery or radiation therapy.');
INSERT INTO CLINICAL_TRIAL_TYPE(id, name, clinical_trial_type_description) VALUES ('912ced79-8d17-405a-a770-f3b9a1b076ae', 'Prevention', 'Prevention research looks for better ways to prevent disorders from developing or returning. Different kinds of prevention research may study medicines, vitamins, vaccines, minerals, or lifestyle changes.');
INSERT INTO CLINICAL_TRIAL_TYPE(id, name, clinical_trial_type_description) VALUES ('010cce3a-aebd-4244-9e4c-7ca96f2f225f', 'Diagnostic', 'This refers to the practice of looking for better ways to identify a particular disorder or condition.');
INSERT INTO CLINICAL_TRIAL_TYPE(id, name, clinical_trial_type_description) VALUES ('44ab8d69-e073-445e-969a-f66303a5761d', 'Screening', 'Screening research aims to find the best ways to detect certain disorders or health conditions.');
INSERT INTO CLINICAL_TRIAL_TYPE(id, name, clinical_trial_type_description) VALUES ('c9d8fdcc-f0c9-4fc3-ae4e-634bd445b878', 'Genetic studies', 'Genetic studies aim to improve the prediction of disorders by identifying and understanding how genes and illnesses may be related. Research in this area may explore ways in which a person’s genes make him or her more or less likely to develop a disorder. This may lead to development of tailor-made treatments based on a patient’s genetic make-up.');
INSERT INTO CLINICAL_TRIAL_TYPE(id, name, clinical_trial_type_description) VALUES ('a5541d22-0f88-4b5b-ab1d-9a29756b774b', 'Epidemiological studies', 'Epidemiological studies seek to identify the patterns, causes, and control of disorders in groups of people.');


-- CLINICAL TRIAL PHASES
INSERT INTO CLINICAL_TRIAL_PHASE(id, name, clinical_trial_phase_description) VALUES ('3ef9ff99-126e-4eed-88a3-f4cdc15da122', 'Phase I trials', 'Researchers test an experimental drug or treatment in a small group of people for the first time. The researchers evaluate the treatment’s safety, determine a safe dosage range, and identify side effects.');
INSERT INTO CLINICAL_TRIAL_PHASE(id, name, clinical_trial_phase_description) VALUES ('73561c78-0e22-48f5-a3dd-c05a6db223bd', 'Phase II trials', 'The experimental drug or treatment is given to a larger group of people to see if it is effective and to further evaluate its safety.');
INSERT INTO CLINICAL_TRIAL_PHASE(id, name, clinical_trial_phase_description) VALUES ('ae96200d-aee6-4965-a14f-6d4b63b3b1b3', 'Phase III trials', 'The experimental study drug or treatment is given to large groups of people. Researchers confirm its effectiveness, monitor side effects, compare it to commonly used treatments, and collect information that will allow the experimental drug or treatment to be used safely.');
INSERT INTO CLINICAL_TRIAL_PHASE(id, name, clinical_trial_phase_description) VALUES ('d3ae3403-6296-4f4a-a8b5-178e230f36db', 'Phase IV trials', 'Post-marketing studies, which are conducted after a treatment is approved for use by the FDA, provide additional information including the treatment or drug’s risks, benefits, and best use.');

-- TARGET GROUP ATTRIBUTES
INSERT INTO TARGET_GROUP_ATTRIBUTE(id, name, min_age, max_age, target_group_description) VALUES ('d721f48e-42ca-4158-9182-25a5ef460df9', 'Infancy', 0, 2, '0–2 years');
INSERT INTO TARGET_GROUP_ATTRIBUTE(id, name, min_age, max_age, target_group_description) VALUES ('58e017fb-7f00-41d8-af24-c0baf5eca7b6', 'Early Childhood', 2, 4, ' 2–4 years');
INSERT INTO TARGET_GROUP_ATTRIBUTE(id, name, min_age, max_age, target_group_description) VALUES ('26eac54c-93ab-4c87-9a02-006dcf94a929', 'Preschool', 4, 5, '4–5 years');
INSERT INTO TARGET_GROUP_ATTRIBUTE(id, name, min_age, max_age, target_group_description) VALUES ('dba2780d-f4e9-4a2e-9edf-aefc63b71b85', 'School age', 5, 12, '5–12 years');
INSERT INTO TARGET_GROUP_ATTRIBUTE(id, name, min_age, max_age, target_group_description) VALUES ('89ee3a8d-7a76-497a-abd7-95ca35ab9285', 'Adolescence', 13, 19,'13–19 years');
INSERT INTO TARGET_GROUP_ATTRIBUTE(id, name, min_age, max_age, target_group_description) VALUES ('a3dc9c77-f15c-4d7b-bec8-f2dd72d081d4', 'Early adulthood', 20, 39,'20-39 years');
INSERT INTO TARGET_GROUP_ATTRIBUTE(id, name, min_age, max_age, target_group_description) VALUES ('39daf4f6-d245-4e44-bd71-d43bf3d41985', 'adulthood', 40, 64,'40–64 years');
INSERT INTO TARGET_GROUP_ATTRIBUTE(id, name, min_age, max_age, target_group_description) VALUES ('b22ff852-b7bd-44a0-a2d9-68ca5b623528', 'Old Age', 65, 120,'65+ years');

-- CLINICAL TRIALS
INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id, target_group_id) VALUES ('ab87fc90-3151-4a2f-955f-3919b7b0d014', 'Gravidem-120LK', CURRENT_DATE(), DATEADD('YEAR', 1, CURRENT_DATE), 'Investigating a drug to treat Sputgravaxia, a condition suffering from body odor, acid reflux, and uncontrollable weeping.', 'Vestibulum dapibus orci nisl, et mattis purus suscipit id. Vestibulum malesuada semper velit, a scelerisque ex. Praesent interdum luctus lacus, nec feugiat erat pharetra vel.', '09aef28a-cfba-4073-aa23-719bd94a0fc5', '3ef9ff99-126e-4eed-88a3-f4cdc15da122', 'a3dc9c77-f15c-4d7b-bec8-f2dd72d081d4');
INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('e458605d-3668-423d-a013-fb22b36f64ab', 'Spinepia-K12P', DATEADD('MONTH', 1, CURRENT_DATE), DATEADD('YEAR', 2, CURRENT_DATE), 'Investigating a drug to treat Sputboobasia, which includes blindness, dwarfism, and swelling of ears.', 'Etiam eget elementum nunc. Sed placerat quam nec elementum consequat. Cras ornare dapibus lobortis. Ut in posuere odio, id fringilla augue. In ullamcorper tortor ligula.', '09aef28a-cfba-4073-aa23-719bd94a0fc5', '3ef9ff99-126e-4eed-88a3-f4cdc15da122', 'dba2780d-f4e9-4a2e-9edf-aefc63b71b85');
INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('79df9fbe-7b6c-43e3-b043-9239b800ea6c', 'Chuckhankopy Research', DATEADD('MONTH', 8, CURRENT_DATE), DATEADD('YEAR', 2, CURRENT_DATE), 'Study to help people reduce sleepwalking and clammy hands', 'Pellentesque quis sodales justo. Aliquam ac ornare lectus. Aenean at massa id mauris facilisis sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames.', '912ced79-8d17-405a-a770-f3b9a1b076ae', '3ef9ff99-126e-4eed-88a3-f4cdc15da122', '58e017fb-7f00-41d8-af24-c0baf5eca7b6');
-- INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('36c12a96-2478-4d0f-9d41-6c62cad0f2f8', '', '', '', '', '', '', '');
-- INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('ce29052d-77b4-4f55-8ed4-85af43bf9e35', '', '', '', '', '', '', '');
-- INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('594d34ef-6afc-4baf-b674-4c42a8c82866', '', '', '', '', '', '', '');
-- INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('e85a2610-44a6-4f94-8088-78b87db91642', '', '', '', '', '', '', '');
-- INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('1b9e098b-1546-414b-848e-3c179fcfb558', '', '', '', '', '', '', '');
-- INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('cc40a383-39a2-4569-8340-c7c9938de62d', '', '', '', '', '', '', '');
-- INSERT INTO CLINICAL_TRIAL (id, name, start_date, end_date, clinical_trial_description, clinical_trial_detail, clinical_trial_type_id, clinical_trial_phase_id , target_group_id) VALUES ('7d8d7604-8e67-4eae-938c-8a4b7cbbf30e', '', '', '', '', '', '', '');